#!/bin/sh

usage="config to configure dotfiles, config commit [message] to upload to github"
conf() {
    pth=$PWD
    cd /home/me
    nvim .zshrc
    cd $pth
}

commit() {
    gitpth="/home/me/gitrepo"
    pth=$PWD
    git clone url $gitpth
    cd $gitpth
    cp -f ~/.zshrc zshrc
    cp -f ~/.tmux.conf tmux
    cp -f ~/.profile profile
    cp -f ~/.config/nvim/init.vim vimrc
    cp -f ~/.config/nvim/coc-settings.json coc-settings.json
    cp -f ~/.config/nvim/plugins/* neovim/plugins/
    cp -f ~/.config/nvim/lua/* neovim/lua/
    cp -f ~/README.md README.md
    git add :
    git commit -m "$1"
    git push
}

case "$1" in
    "") conf ;;
    "commit") commit "$2" ;;
    *) echo "$usage" ;;
esac
